### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by lmxmercy** [ZacharyWang-007/Surformer#1]
Hi! A nice work and thx for your code publicly.
1. Could u tell me how to separate the low-risk and high-risk, an average value? a median value? or some special threshold according to the risk score.
2. How to visualize the heatmap and local interpretation which shown in "Fig. 5. Global and local interpretation of WSIs."?
Thx for your time and waiting for your reply!
Much love, thx!
Mingxin

**Comment by ZacharyWang-007** [comment]
Thanks for your attention. I have replied to your issues through emails. I will close this issue.

**Comment by junjianli106** [comment]
您好，能否发一下您的可视化部分代码？谢谢。（我的邮箱 junjianli@csu.edu.cn）

**Comment by ZacharyWang-007** [comment]
抱歉回复的不及时。 可视化的代码主要参考了 CLAM这个工作，里面有详细的代码可视化工具。 https://github.com/mahmoodlab/CLAM

**Comment by junjianli106** [comment]
好的，谢谢。已经根据clam里面的代码进行了可视化，谢谢。



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 13, 2024 12:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ZacharyWang-007/Surformer] About visualization (Issue #1)




 
抱歉回复的不及时。 可视化的代码主要参考了 CLAM这个工作 （https://github.com/mahmoodlab/CLAM），里面有详细的代码可视化工具。
